name: eeg-pytorch
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py39hf3d152e_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.69.1=h5202010_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=h28cd5cc_2
  - hdf5=1.10.6=nompi_h3c11f04_101
  - hdf5storage=0.1.16=pyh44b312d_0
  - icu=58.2=hf484d3e_1000
  - intel-openmp=2021.3.0=h06a4308_3350
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py39h2531618_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.3.4=py39h06a4308_0
  - matplotlib-base=3.3.4=py39h62a2d02_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.0=py39h42c9631_2
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.20.3=py39hf144106_0
  - numpy-base=1.20.3=py39h74d4b33_0
  - olefile=0.46=py_0
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1k=h27cfd23_0
  - pcre=8.45=h295c915_0
  - pillow=8.3.1=py39h2c7a002_0
  - pip=21.2.4=py37h06a4308_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py39h2531618_6
  - python=3.9.6=h12debd9_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.9.0=py3.9_cuda10.2_cudnn7.6.5_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - scipy=1.6.2=py39had2a1c9_1
  - setuptools=52.0.0=py39h06a4308_0
  - sip=4.19.13=py39h2531618_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.9.0=py39
  - torchvision=0.10.0=py39_cu102
  - tornado=6.1=py39hbd71b63_0
  - tzdata=2021a=h5d7bf9c_0
  - wheel=0.37.0=pyhd3eb1b0_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.4.0
    - appdirs==1.4.4
    - astunparse==1.6.3
    - audioread==3.0.0
    - braindecode==0.6
    - cachetools==5.3.0
    - cffi==1.15.1
    - charset-normalizer==2.0.12
    - coverage==5.5
    - decorator==5.1.1
    - flatbuffers==23.3.3
    - gast==0.4.0
    - google-auth==2.16.2
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grad-cam==1.4.0
    - grpcio==1.51.3
    - h5py==3.6.0
    - idna==3.3
    - importlib-metadata==6.0.0
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsonpatch==1.32
    - jsonpointer==2.3
    - kapre==0.3.7
    - keras==2.11.0
    - lazy-loader==0.1
    - libclang==15.0.6.1
    - librosa==0.10.0.post1
    - llvmlite==0.39.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - mlxtend==0.21.0
    - mne==1.0.3
    - moabb==0.4.6
    - msgpack==1.0.5
    - networkx==2.8.7
    - numba==0.56.4
    - oauthlib==3.2.2
    - opencv-python==4.5.5.62
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.3.2
    - pooch==1.6.0
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pyriemann==0.2.7
    - pytz==2021.1
    - pywavelets==1.4.1
    - pyyaml==5.4.1
    - pyzmq==24.0.1
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.1.1
    - seaborn==0.11.2
    - skorch==0.11.0
    - soundfile==0.12.1
    - soxr==0.3.4
    - tabulate==0.8.9
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==2.2.0
    - torchinfo==1.6.5
    - torchsummary==1.5.1
    - tqdm==4.62.2
    - ttach==0.0.3
    - typing-extensions==4.5.0
    - urllib3==1.26.9
    - visdom==0.2.1
    - websocket-client==1.4.1
    - werkzeug==2.2.3
    - wrapt==1.15.0
    - zipp==3.15.0
prefix: /home/dl/anaconda3/envs/eeg-pytorch

